### ISSUE TITLE
Not working when the image is a link

### ISSUE THREAD

**Issue by amiguet** [LionelHolt/thunderbird-compose-responsive-images#1]
Hello,

First of all many thanks for this extension! I've been waiting for this for ages, and this is soooo much better than hand-editing the generated html each time I include an image! :-D

However, I noticed that if the image is a link, the extension doesn't kick in.

Steps to reproduce:
When composing a message
- Insert -> Image
- Select a local file
- In the 4th tab ("Link"), enter a URL
- click OK

The image's width and height are fixed and not responsive.

Thunderbird 102.6.0 on Linux, Compose Responsive Images 0.9

**Comment by LionelHolt** [comment]
Thank you for the kind words and for using my extension!

I am working on it now ...

**Comment by LionelHolt** [comment]
Done!

And it would make my day to see my first 5-star review. 😉

https://addons.thunderbird.net/en-US/thunderbird/addon/compose-responsive-images

**Comment by LionelHolt** [comment]
Oh and it would make my day to see my first 5-star review. 😉

https://addons.thunderbird.net/en-US/thunderbird/addon/compose-responsive-images
